// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxvoosbxuxkvvwoxitsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4dm9vc2J4dXhrdnZ3b3hpdHNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5MzAzMzAsImV4cCI6MjA1MzUwNjMzMH0.cMOGf3_wh7O40Cvejgn5VjdPeI7IzBYbGszbbWxg_uI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);